# Site
name: 'Azure Blog'
description: 'My Azure Blog.'
#logo: 'assets/images/logo.png'
#favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'sven@malvik.de'
mailchimp-list: 'http://eepurl.com/hnE_Zf'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    svenmalvik:
      name:           Sven Malvik
      site:           https://www.svenmalvik.com
      avatar:         https://cdn.svenmalvik.com/images/svenmalvik.jpg
      bio:            "Hello, I am Sven Malvik, a Microsoft Azure MVP."
      email: "sven@malvik.de"
      facebook: svenmalvik
      github: svenmalvik
      linkedin: https://www.linkedin.com/in/svenmalvik/
      stackoverflow: "1025692/sven-malvik"
    #  snapchat: deanat78
    #  instagram: deanat78
      youtube: user/svenmalvik
    #  twitch: yourname
    #  twitter: https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: svenmalvik
      avatar: https://www.svenmalvik.com/img/svenmalvik.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]